using System.Globalization;

namespace QuickAccess;

public static class Loc
{
    public static string Lang { get; private set; } = "en";

    public static void SetLanguage(string preference)
    {
        if (preference == "ru") Lang = "ru";
        else if (preference == "en") Lang = "en";
        else Lang = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "ru" ? "ru" : "en";
    }

    public static CultureInfo Culture => CultureInfo.GetCultureInfo(Lang == "ru" ? "ru-RU" : "en-US");

    public static string T(string key, params object?[] args)
    {
        var dict = Lang == "ru" ? Ru : En;
        if (!dict.TryGetValue(key, out var s))
            s = En.TryGetValue(key, out var fb) ? fb : key;
        return args.Length == 0 ? s : string.Format(s, args);
    }

    private static readonly Dictionary<string, string> En = new()
    {
        ["bar.add"] = "+ Group",
        ["bar.hide"] = "To tray (Esc)",
        ["bar.autoOn"] = "Autostart: on",
        ["bar.autoOff"] = "Autostart: off",
        ["bar.settings"] = "⚙ Settings",
        ["bar.edit"] = "✏ Arrange",
        ["bar.finish"] = "✓ Finish arranging",
        ["bar.modules"] = "🧩 Modules",
        ["bar.hint"] = "Show/hide: {0} • Right-click a group for menu • Right-click background for new group",
        ["bar.hintEdit"] = "Arrange mode: drag groups and shortcuts with LMB • launch disabled • ✓ finish to save",
        ["tray.show"] = "Show ({0})",
        ["tray.diag"] = "Diagnostics",
        ["tray.auto"] = "Autostart",
        ["tray.exit"] = "Exit",
        ["tray.balloonT"] = "QuickAccess running",
        ["tray.balloon"] = "I'm in the tray. Press {0} for the panel.",
        ["tray.diagT"] = "QuickAccess — diagnostics",
        ["msg.hotkeyFail"] = "Could not register hotkeys.\n{0}\n\nYou can open the panel via the tray icon (double-click).",
        ["msg.hotkeyT"] = "QuickAccess — hotkey",
        ["msg.launchFail"] = "Could not launch:\n{0}\n{1}",
        ["ctx.rename"] = "Rename",
        ["ctx.addShortcut"] = "Add shortcut",
        ["ctx.pickIcon"] = "Choose icon…",
        ["ctx.delGroup"] = "Delete group",
        ["ctx.del"] = "Delete",
        ["prompt.newGroupT"] = "New group",
        ["prompt.newGroupL"] = "Group name:",
        ["prompt.renameT"] = "Rename",
        ["prompt.renameL"] = "New name:",
        ["prompt.scT"] = "Shortcut",
        ["prompt.scNameL"] = "Name:",
        ["prompt.ok"] = "OK",
        ["prompt.cancel"] = "Cancel",
        ["dlg.openTitle"] = "Shortcut for '{0}' — choose .exe/.lnk",
        ["icon.groupT"] = "Group icon",
        ["icon.scT"] = "Shortcut icon",
        ["icon.none"] = "No icon",
        ["icon.noSel"] = "No icon selected",
        ["icon.cur"] = "Current: {0}",
        ["del.groupT"] = "Delete group",
        ["del.groupQ"] = "Delete group '{0}' and all its shortcuts?",
        ["del.scT"] = "Delete shortcut",
        ["del.scQ"] = "Delete shortcut '{0}'?",
        ["del.confirmT"] = "Confirm",
        ["dlg.yes"] = "Yes, delete",
        ["set.title"] = "QuickAccess Settings",
        ["set.header"] = "Settings",
        ["set.thickness"] = "Line thickness: {0:0.#}",
        ["set.tension"] = "Web tension: {0:0.00}",
        ["set.theme"] = "Theme",
        ["set.snap"] = "Snap to grid",
        ["set.auto"] = "Start with Windows",
        ["set.done"] = "Done",
        ["set.hotkeys"] = "Hotkeys",
        ["set.main"] = "Primary:",
        ["set.secondary"] = "Secondary:",
        ["set.press"] = "Press combination…",
        ["set.reset"] = "Reset",
        ["set.language"] = "Language",
        ["set.langAuto"] = "Auto",
        ["set.palLines"] = "Lines",
        ["set.palAccent"] = "Accent",
        ["set.palBg"] = "Button background",
        ["mod.title"] = "QuickAccess Modules",
        ["mod.header"] = "Modules",
        ["mod.soon"] = "New community modules will appear here. Switch off anything you don't need.",
        ["mod.clockN"] = "Clock widget",
        ["mod.clockD"] = "Live clock in the center of the web.",
        ["mod.springN"] = "Spring physics",
        ["mod.springD"] = "Shortcut threads stretch and wobble when you drag a group.",
        ["tip.delGroup"] = "Delete group",
        ["tip.delShortcut"] = "Delete shortcut",
    };

    private static readonly Dictionary<string, string> Ru = new()
    {
        ["bar.add"] = "+ Группа",
        ["bar.hide"] = "В трей (Esc)",
        ["bar.autoOn"] = "Автозапуск: вкл",
        ["bar.autoOff"] = "Автозапуск: выкл",
        ["bar.settings"] = "⚙ Настройки",
        ["bar.edit"] = "✏ Режим расстановки",
        ["bar.finish"] = "✓ Завершить расстановку",
        ["bar.modules"] = "🧩 Модули",
        ["bar.hint"] = "Показать/скрыть: {0} • ПКМ по группе — меню • ПКМ по фону — новая группа",
        ["bar.hintEdit"] = "Режим расстановки: тяни группы и ярлыки ЛКМ • запуск отключен • ✓ заверши для сохранения",
        ["tray.show"] = "Показать ({0})",
        ["tray.diag"] = "Диагностика",
        ["tray.auto"] = "Автозапуск",
        ["tray.exit"] = "Выход",
        ["tray.balloonT"] = "QuickAccess запущен",
        ["tray.balloon"] = "Я в трее. Нажми {0} для панели.",
        ["tray.diagT"] = "QuickAccess — диагностика",
        ["msg.hotkeyFail"] = "Не удалось зарегистрировать хоткеи.\n{0}\n\nПанель можно открыть через иконку в трее (двойной клик).",
        ["msg.hotkeyT"] = "QuickAccess — хоткей",
        ["msg.launchFail"] = "Не удалось запустить:\n{0}\n{1}",
        ["ctx.rename"] = "Переименовать",
        ["ctx.addShortcut"] = "Добавить ярлык",
        ["ctx.pickIcon"] = "Выбрать иконку…",
        ["ctx.delGroup"] = "Удалить группу",
        ["ctx.del"] = "Удалить",
        ["prompt.newGroupT"] = "Новая группа",
        ["prompt.newGroupL"] = "Имя группы:",
        ["prompt.renameT"] = "Переименовать",
        ["prompt.renameL"] = "Новое имя:",
        ["prompt.scT"] = "Ярлык",
        ["prompt.scNameL"] = "Название:",
        ["prompt.ok"] = "OK",
        ["prompt.cancel"] = "Отмена",
        ["dlg.openTitle"] = "Ярлык для '{0}' — выбери .exe/.lnk",
        ["icon.groupT"] = "Иконка группы",
        ["icon.scT"] = "Иконка ярлыка",
        ["icon.none"] = "Без иконки",
        ["icon.noSel"] = "Иконка не выбрана",
        ["icon.cur"] = "Текущая: {0}",
        ["del.groupT"] = "Удаление группы",
        ["del.groupQ"] = "Удалить группу '{0}' и все её ярлыки?",
        ["del.scT"] = "Удаление ярлыка",
        ["del.scQ"] = "Удалить ярлык '{0}'?",
        ["del.confirmT"] = "Подтверждение",
        ["dlg.yes"] = "Да, удалить",
        ["set.title"] = "Настройки QuickAccess",
        ["set.header"] = "Настройки",
        ["set.thickness"] = "Толщина линий: {0:0.#}",
        ["set.tension"] = "Натяжение паутины: {0:0.00}",
        ["set.theme"] = "Тема",
        ["set.snap"] = "Привязка к сетке (Snap to Grid)",
        ["set.auto"] = "Автозапуск вместе с Windows",
        ["set.done"] = "Готово",
        ["set.hotkeys"] = "Горячие клавиши",
        ["set.main"] = "Основная:",
        ["set.secondary"] = "Запасная:",
        ["set.press"] = "Нажмите комбинацию…",
        ["set.reset"] = "Сбросить",
        ["set.language"] = "Язык",
        ["set.langAuto"] = "Авто",
        ["set.palLines"] = "Линии",
        ["set.palAccent"] = "Акцент",
        ["set.palBg"] = "Фон кнопок",
        ["mod.title"] = "Модули QuickAccess",
        ["mod.header"] = "Модули",
        ["mod.soon"] = "Новые модули от сообщества появятся здесь. Отключайте ненужное.",
        ["mod.clockN"] = "Виджет часов",
        ["mod.clockD"] = "Живые часы в центре паутины.",
        ["mod.springN"] = "Пружинная физика",
        ["mod.springD"] = "Нити ярлыков натягиваются и колеблются при перетаскивании группы.",
        ["tip.delGroup"] = "Удалить группу",
        ["tip.delShortcut"] = "Удалить ярлык",
    };
}
